version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-22.9"

sphinx:
  configuration: doc/_source/conf.py

conda:
  environment: doc/environment.yml

python:
  install:
    - method: pip
      path: .
