conda:
  environment: docs/environment.yml  
python:
  version: 3.7
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs    
  setup_py_install: true
  system_packages: true

