name: pylbm-env
channels:
  - conda-forge
dependencies:
  - numpy
  - numpy-stl
  - matplotlib
  - sympy
  - cython<3
  - h5py
  - mpi4py
  - colorlog
  - colorama
  - cerberus
  - jinja2
  - pytest
  - pylint
  - typed-ast
  - pytest
  - pytest-cov
  - pytest-mpl
  - codecov
  - ipywidgets
  - nbval
  - flake8
  - pip:
      - pytest-pylint==0.21
