# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # python-version: [3.7, 3.8, 3.9, "3.10"]
        sympy-version: [1.8, 1.9, "1.10", "1.11"]
        mpi:
          - openmpi
          - msmpi
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        exclude:
          - os: ubuntu-latest
            mpi: msmpi
          - os: macos-latest
            mpi: msmpi
          - os: windows-latest
            mpi: openmpi

    steps:
      - uses: actions/checkout@v2

      - name: Install MPI (${{ matrix.mpi }})
        run: bash .github/workflows/mpi/install-${{ matrix.mpi }}.sh

      - name: install mamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: conda/environment.yml
          environment-name: pylbm-env
          extra-specs: |
            sympy=${{ matrix.sympy-version }}

      # - name: Set up Python ${{ matrix.python-version }}
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: ${{ matrix.python-version }}

      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install flake8 pytest
      #     pip install -r requirements-dev.txt
      #     pip install sympy==${{ matrix.sympy-version }}

      - name: Install pylbm
        shell: bash -l {0}
        run: |
          pip install .

      - name: Lint with flake8
        shell: bash -l {0}
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test with pytest
        shell: bash -l {0}
        run: |
          pytest --pylint --pylint-rcfile=.pyrcfile --pylint-error-types=EF pylbm
          pytest --nbval-lax notebooks
          cd tests; pytest --mpl --h5diff -m "not slow" --cov=pylbm
